name: Deploy Quarto Website

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.6.39'

      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: '4.2.0'

      # - name: Install R Dependencies
      #   run: |
      #     install.packages(c(
      #       # 'base64enc',
      #       # 'bslib',
      #       # 'cachem',
      #       # 'cli',
      #       # 'digest',
      #       # 'evaluate',
      #       # 'fastmap',
      #       # 'fontawesome',
      #       # 'fs',
      #       # 'glue',
      #       # 'highr',
      #       # 'htmltools',
      #       # 'jquerylib',
      #       # 'jsonlite',
      #       'knitr',
      #       'lifecycle',
      #       'magrittr',
      #       'memoise',
      #       'mime',
      #       'R6',
      #       'rappdirs',
      #       'rlang',
      #       'rmarkdown',
      #       'sass',
      #       'stringi',
      #       'stringr',
      #       'tinytex',
      #       'vctrs',
      #       'xfun',
      #       'yaml'
      #     ))
      #   shell: Rscript {0}

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: mywebsite/ 

      - name: Setup Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v1
        with:
          path: mywebsite/_site  

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v2
